# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {Place 30-675}  -string {{ERROR: [Place 30-675] Sub-optimal placement for a global clock-capable IO pin and BUFG pair.If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
	< set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets PButton_0_IBUF_inst/O] >

	PButton_0_IBUF_inst/IBUFCTRL_INST (IBUFCTRL.O) is locked to IOB_X0Y55
	 PButton_0_IBUF_BUFG_inst (BUFGCE.I) is provisionally placed by clockplacer on BUFGCE_HDIO_X0Y10

	The above error could possibly be related to other connected instances. Following is a list of 
	all the related clock rules and their respective instances.

	Clock Rule: rule_bufgce_bufg_conflict
	Status: PASS 
	Rule Description: Only one of the 2 available sites (BUFGCE or BUFGCE_DIV/BUFGCTRL) in a pair can be
	used at the same time
	 and PButton_0_IBUF_BUFG_inst (BUFGCE.O) is provisionally placed by clockplacer on BUFGCE_HDIO_X0Y10

Resolution: A dedicated routing path between the two can be used if: (a) The global clock-capable IO (GCIO) is placed on a GCIO capable site (b) The BUFG is placed in the same bank of the device as the GCIO pin. Both the above conditions must be met at the same time, else it may lead to longer and less predictable clock insertion delays.}}  -suppress 
set_msg_config  -id {Place 30-675}  -string {{ERROR: [Place 30-675] Sub-optimal placement for a global clock-capable IO pin and BUFG pair.If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
	< set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets PButton_0_IBUF_inst/O] >

	PButton_0_IBUF_inst/IBUFCTRL_INST (IBUFCTRL.O) is locked to IOB_X0Y55
	 PButton_0_IBUF_BUFG_inst (BUFGCE.I) is provisionally placed by clockplacer on BUFGCE_X0Y24

	The above error could possibly be related to other connected instances. Following is a list of 
	all the related clock rules and their respective instances.

	Clock Rule: rule_bufgce_bufg_conflict
	Status: PASS 
	Rule Description: Only one of the 2 available sites (BUFGCE or BUFGCE_DIV/BUFGCTRL) in a pair can be
	used at the same time
	 and PButton_0_IBUF_BUFG_inst (BUFGCE.O) is provisionally placed by clockplacer on BUFGCE_X0Y24

Resolution: A dedicated routing path between the two can be used if: (a) The global clock-capable IO (GCIO) is placed on a GCIO capable site (b) The BUFG is placed in the same bank of the device as the GCIO pin. Both the above conditions must be met at the same time, else it may lead to longer and less predictable clock insertion delays.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu48dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.cache/wt [current_project]
set_property parent.project_path C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/raque/OneDrive/Documentos/master/TFM/RFSoC4x2-BSP/board_files/rfsoc4x2/1.0} [current_project]
set_property board_part realdigital.org:rfsoc4x2:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_6/design_1_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_6/design_1_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_6/design_1_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_7/design_1_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_7/design_1_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_7/design_1_auto_ds_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_8/design_1_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_8/design_1_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_ds_8/design_1_auto_ds_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_xpm_cdc_gen_0_1/synth/design_1_xpm_cdc_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_xpm_cdc_gen_0_1/design_1_xpm_cdc_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_1/design_1_axi_gpio_3_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_1/design_1_axi_gpio_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_1/design_1_axi_gpio_3_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/bd_365d_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/bd_365d_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_2/design_1_axi_gpio_3_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_2/design_1_axi_gpio_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_2/design_1_axi_gpio_3_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/data/startup.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.srcs/constrs_1/new/RFSoCoverlay.xdc
set_property used_in_implementation false [get_files C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay_v2/RFSoCoverlay.srcs/constrs_1/new/RFSoCoverlay.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/RFSoCoverlay/RFSoCoverlay.srcs/utils_1/imports/synth_1/DACRAMstreamer.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xczu48dr-ffvg1517-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
