#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Sep 01 13:56:17 +0200 2023
# SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_12 zynq_ultra_ps_e_vip_v1_0_12 xil_defaultlib generic_baseblocks_v2_1_0 axi_register_slice_v2_1_26 fifo_generator_v13_2_7 axi_data_fifo_v2_1_25 axi_crossbar_v2_1_27 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_28 gigantic_mux xpm_cdc_gen_v1_0_1 axi_protocol_converter_v2_1_26 axi_clock_converter_v2_1_25 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_26)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_block.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm_top.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_bgt_fsm.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_device_rom.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm_disabled.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_tile_config.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_constants_config.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_arbiter.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_arbiter_adc.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_register_decode.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_address_decoder.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_axi_lite_ipif.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_counter_f.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_pselect_f.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_slave_attachment.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_rf_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_control_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_control.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_access_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_irq_req_ack.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_irq_sync.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0bufg_gt_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_overvol_irq.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_powerup_state_irq.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_sysref_count.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_data_align.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_fifo_ctrl.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_rst_cnt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_clk_detection.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/5390/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/3fa0/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_99M_0/sim/design_1_rst_ps8_0_99M_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/sim/design_1_rst_usp_rf_data_converter_0_307M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_28 $vhdlan_opts \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/3ed9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_4_0/sim/design_1_axi_gpio_4_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_2/sim/design_1_axi_gpio_0_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_0/sim/design_1_axi_gpio_1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_3_0/sim/design_1_axi_gpio_3_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_1/sim/design_1_axi_gpio_1_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_4/sim/design_1_axi_gpio_1_4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_5/sim/design_1_axi_gpio_1_5.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/bd_0/sim/bd_36ad.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/bd_0/ip/ip_0/sim/bd_36ad_ila_lib_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/bd_0/ip/ip_1/bd_36ad_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/bd_0/ip/ip_1/sim/bd_36ad_g_inst_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/sim/design_1_system_ila_2_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_ds_buf_0_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_ds_buf_0_0/sim/design_1_util_ds_buf_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_1/sim/design_1_proc_sys_reset_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_mon.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_family.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm_cdc_gen_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4c7c/hdl/xpm_cdc_gen_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_0/sim/design_1_xpm_cdc_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_1_1/bd_0/sim/bd_f69c.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/sim/bd_f69c_ila_lib_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_1_1/sim/design_1_system_ila_1_1.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/a918/src/RFSoC_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/a918/src/params_generator.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/a918/src/DAC_generator.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_DAC_generator_16w_0_0/sim/design_1_DAC_generator_16w_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/90c8/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/e893/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b3c7/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pruebas_RF.gen/sources_1/bd/design_1/ipshared/fd26/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
