set_property SRC_FILE_INFO {cfile:C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.srcs/constrs_1/imports/4x2_PL_FULL_CONSTRAINTS/4x2_LED_PB__SW.xdc rfile:../../../pruebas_RF.srcs/constrs_1/imports/4x2_PL_FULL_CONSTRAINTS/4x2_LED_PB__SW.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.srcs/constrs_1/imports/new/RFSoCoverlay.xdc rfile:../../../pruebas_RF.srcs/constrs_1/imports/new/RFSoCoverlay.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.srcs/constrs_1/imports/4x2_PL_FULL_CONSTRAINTS/4x2_PMOD.xdc rfile:../../../pruebas_RF.srcs/constrs_1/imports/4x2_PL_FULL_CONSTRAINTS/4x2_PMOD.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AV12 IOSTANDARD LVCMOS18} [ get_ports { PButton_0 } ]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AV10 IOSTANDARD LVCMOS18} [ get_ports { PB_1 } ]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AW9 IOSTANDARD LVCMOS18} [ get_ports { PB_2 } ]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AT12 IOSTANDARD LVCMOS18} [ get_ports { PB_3 } ]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AN12 IOSTANDARD LVCMOS18} [ get_ports { PB_4 } ]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets PButton_0_IBUF_inst/O]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP18 [get_ports PL_SYSREF[0]]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN11 [get_ports PL_CLK[0]]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF16 [ get_ports "PMOD0_0" ]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG17 [ get_ports "PMOD0_1" ]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ16 [ get_ports "PMOD0_2" ]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [ get_ports "PMOD0_3" ]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF15 [ get_ports "PMOD0_4" ]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF17 [ get_ports "PMOD0_5" ]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH17 [ get_ports "PMOD0_6" ]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16 [ get_ports "PMOD0_7" ]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW13 [ get_ports "PMOD1_0" ]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR13 [ get_ports "PMOD1_1" ]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13 [ get_ports "PMOD1_2" ]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13 [ get_ports "PMOD1_3" ]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU15 [ get_ports "PMOD1_4" ]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP14 [ get_ports "PMOD1_5" ]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15 [ get_ports "PMOD1_6" ]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14 [ get_ports "PMOD1_7" ]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports "PMOD1*"]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW16 [ get_ports "PMOD01_0" ]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15 [ get_ports "PMOD01_1" ]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW14 [ get_ports "PMOD01_2" ]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR16 [ get_ports "PMOD01_3" ]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV16 [ get_ports "PMOD01_4" ]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT16 [ get_ports "PMOD01_5" ]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports "PMOD01*"]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATIONAL_LOOPS TRUE [get_nets "design_1/hier_DACgeneration/DAC_generator_16w_0/alg_end"]
