# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.srcs/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0.xci
# IP: The module: 'design_1_rst_usp_rf_data_converter_0_307M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.gen/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_usp_rf_data_converter_0_307M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.gen/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_usp_rf_data_converter_0_307M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.gen/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_usp_rf_data_converter_0_307M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.srcs/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0.xci
# IP: The module: 'design_1_rst_usp_rf_data_converter_0_307M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.gen/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_usp_rf_data_converter_0_307M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.gen/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_usp_rf_data_converter_0_307M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raque/OneDrive/Documentos/master/TFM/Vivado/PL_MODEL/pruebas_RF.gen/sources_1/bd/design_1/ip/design_1_rst_usp_rf_data_converter_0_307M_0/design_1_rst_usp_rf_data_converter_0_307M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_usp_rf_data_converter_0_307M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
